[general]
# Alacritty disabled per user request
# import = [
#     "~/.config/alacritty/themes/themes/selenized_light.toml"
# ]

[env]
TERM = "xterm-256color"

[window]
# decorations = "Buttonless"   # 隐藏 macOS 标题栏
dynamic_padding = false
# opacity = 0.9

[window.padding]
x = 10
y = 10

[font]
size = 15.0

# [colors.primary]
# background = "#1E1E2E"
# foreground = "#D0CFCF"