gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - '#268bd2'
      - bold
    inactiveBorderColor:
      - '#93a1a1'
    optionsTextColor:
      - '#268bd2'
    selectedLineBgColor:
      - '#eee8d5'
    cherryPickedCommitBgColor:
      - '#eee8d5'
    cherryPickedCommitFgColor:
      - '#268bd2'
    unstagedChangesColor:
      - '#dc322f'
    defaultFgColor:
      - '#657b83'
    searchingActiveBorderColor:
      - '#b58900'
