# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
light = "rose-pine-dawn"

# Alternatives:
# light = "catppuccin-latte"
#dark = "kanagawa-lotus"

# Local tweaks for better status bar contrast on light background
[status]
overall = { fg = "#4d699b", bg = "#fbf1c7", bold = true }
