# Initialize Zim
export LANG=zh_CN.UTF-8
export LC_CTYPE=zh_CN.UTF-8
unset LC_ALL
#

# common
source ~/.config/env/common/all.zsh

# local
# export PLATFORM=$(uname -s)
# source ~/.config/env/local/${PLATFORM}.sh

# zim
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/lazyload.zsh
# source ~/.config/zsh/load.sh

# zsh
# source ~/.config/zsh/vi.zsh
source ~/.config/zsh/emacs.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh
source ~/.config/zsh/tmux.zsh
[[ -r ~/.config/zsh/zstyles.zsh ]] && source ~/.config/zsh/zstyles.zsh
# fpath 由 lazyload.zsh 在 compinit 前统一处理，这里无需重复设置
 fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
 fpath=(/usr/share/zsh/5.9/functions $fpath)

# source ~/.config/zsh/git-alias-descriptions.zsh

# Git/JJ enhanced completion are lazy-loaded via lazyload.zsh
# source ~/.config/zsh/git-completion-enhanced.zsh
# source ~/.config/zsh/jj-completion-enhanced.zsh

# fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
#
