PS1="[\u@\h \W]\$ "

# common
. ~/.config/env/common/all.zsh

# local
export PLATFORM=$(uname -s)
. ~/.config/env/local/${PLATFORM}.sh

# bash


# Return early for non-interactive shells
[[ $- == *i* ]] || return

# fzf
. ~/.config/bash/fzf.sh
